#Configuração do docker-compose para o projeto Spring Boot

#version: "3.8" #versão do docker-compose

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_mobiauto
    restart: always
    environment:
      MYSQL_DATABASE: AutoDealDB
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3308:3306"
    volumes:
    #  - mysqlDB_data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysqlDB_data:
