server:
  servlet:
    context-path: /mobi
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/AutoDealDB?useSSL=false&createDatabaseIfNotExists=true&allowPublicKeyRetrieval=true&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        jdbc:
          lob:
            new_contextual_creation: true
        type:
          preferred_uuid_jdbc_type: CHAR

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    logging:
      level:
        org.springframework.security: DEBUG

admin:
  email: admin@revenda.com
  senha: admin


